fnbi:
  executable_path: "C:\\Program Files (x86)\\Fortinet\\FortiNBI\\FortiNBI.exe"
browser:
  chrome_user_data_dir: "C:\\Users\\test\\AppData\\Local\\Google\\Chrome\\User Data"
  chrome_profile_directory: "Profile 1"
test:
  allowed_url: "https://www.example.com"
  blocked_url: "https://www.dropbox.com"
  freeze_url: "https://www.cisco.com"
  isolate_url: "https://www.facebook.com"